name: Java CI

on: [ push ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.19
        uses: actions/setup-java@v1
        with:
          java-version: 1.19
      - name: Test with Maven
        run: mvn -B test --file pom.xml
